### ISSUE TITLE
--inplace ?

### ISSUE THREAD

**Issue by stuaxo** [abarker/strip-hints#13]
Hi,
   I've got a big project I'd like to strip the hints from automatically (our hints are for 3.9, but I want to try testing our project in pypy or pyston which only support 3.8).

Is there any chance of adding an --inplace option, then I can pass strip-hints all the files to strip their hints.

Cheers
Stuart

**Comment by abarker** [comment]
I've added both an `--outfile` and `--inplace` option, as well as a `--help` option, in the current version at GH.  I'll push it to pypi after a few more tests.

**Comment by antunesleo** [comment]
Pretty good! I'm also interested in this feature. 
I was trying to do this update in place on bash this way `strip-hints module.py > module.py` , but for some reason I couldn't understand why, the result is a **module.py being a empty file**.
 If we do this way `strip-hints module.py > module.foo.py` it works, but we have to manually copy the new content to the file :cry:

**Comment by abarker** [comment]
Version 0.1.10 with the new options is now up at PyPI.
