### ISSUE TITLE
Check-only feature

### ISSUE THREAD

**Issue by ghost** [abarker/strip-hints#3]
This is a feature request and not an issue. It would be great if we could pass a `check_only` parameter in order to see if there are any typehints which would be removed by actually running the stripper. My use case is that I would like to add a check in my CI pipeline making sure no python3.5 incompatible typehints have been added to the code.

**Comment by abarker** [comment]
I've added an option `--only-test-for-changes` which does what you suggested.  It is documented on the main page.  Note that it tests for any changes, including in annotated function parameters (which are supported in Python 3.5).

**Comment by erlendcognite** [comment]
That's awesome. Thank you! I guess if I pass the `--only-assigns-and-defs` flag in addition to `--only-test-for-changes`, it will only test if py3.5 incompatible changes have been made to the code? 

Would be great to be able to do this programatically as well. Adding something like this should do the trick:
```
def test_for_changes(filename, to_empty=False, no_ast=False, no_colon_move=False, only_assigns_and_defs=False):
    # Need to tokenize and untokenize because tokenizer's round-trip guarantee does
    # not guarantee spaces within lines (but usually works).
    processed_code = strip_file_to_string(filename, to_empty=to_empty, no_ast=no_ast, no_colon_move=no_colon_move,
                                          only_assigns_and_defs=only_assigns_and_defs)
    original_tokens = TokenList()
    original_tokens.read_from_file(filename)
    original_tokens_untokenized = original_tokens.untokenize()

    if original_tokens_untokenized == processed_code:
        return False
    else:
        return True
```

I attempted to submit a PR, but could not due to insufficient access rights. Great work on this btw, it's super useful!!

**Comment by abarker** [comment]
Yes, passing both of those flags should work.

I consolidated some of the code for the `strip_file_to_string` function so it can now take
the same arguments as the command-line version (including `only_test_for_changes`,
which causes it to return a boolean instead of a string).
