### ISSUE TITLE
Second variable being stripped in multiple variable definiton on single line 

### ISSUE THREAD

**Issue by dmccrevan** [abarker/strip-hints#7]
In the code below, the second variable "y" is being stripped out of the statement
`
x: int, y: int = 1, 2
`
turns into
`
x              = 1, 2
`

I tried looking through the source to fix this but i can seem to figure it out.

**Comment by abarker** [comment]
PEP 526 does not support tuple unpacking for annotated assignments, so your example is a syntax error.  [According to the PEP](https://www.python.org/dev/peps/pep-0526/#global-and-local-variable-annotations) you need to annotate the variables separately from the assignment:

```
x: int
y: int
x, y = 1, 2
```

**Comment by dmccrevan** [comment]
Thanks @abarker Didn't realize this isn't supported.
